networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:42
    ports:
      - "443:443"
    networks:
      inception
    restart: always
  #wordpress:
  #mariadb: