volumes:
  mariadb:
    name: mariadb
    driver: local
    diver_opts:
      device: /home/tgriblin/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/tgriblin/data/wordpress
      o: bind
      type: none